development:
  access_key_id: AKIAIECRO4CITSLWPS3Q
  secret_access_key: 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
  bucket: scotch-files
production:
  access_key_id: AKIAIECRO4CITSLWPS3Q
  secret_access_key: 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
  bucket: scotch-files